#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Memoria Externa del Sistema
#+date: 2026-07-04
#+author: Danilo Sebastián Unapucha Unaucho \\ Michael Sornoza \\ Sebastián Arevalo 
#+email: danilo.unapucha@epn.edu.ec
#+language: es
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 29.3 (Org mode 9.6.15)
#+cite_export:

#+options: H:2
#+latex_class: beamer
#+columns: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)
#+beamer_theme: Madrid
#+beamer_color_theme:
#+beamer_font_theme:

#+beamer_inner_theme:
#+beamer_outer_theme:
#+beamer_header:

# PARTE NICOLE
# SUBTEMA 1
* Discos de estado solido
** Discos de estado solido
Un disco de estado solido es formado a partir de componentes de estado
solido lo que significa que usan semiconductores de elementos solidos
como la silicona o galio. Estas memorias tienen chips basados en NANDS
\textbf{Ventajas del los discos de estado solido:}
- \textbf{Velocidad:} Tienen una velocidad de copiado generalmente de
  200 a 550 Mbps bastante mas rapida que los 50 a 120 Mbps de los
  discos duros. 
- \textbf{Uso de energia:} En promedio consumen 2-3 watts prologando
  la duracion de la bateria.
\textbf{Desventajas de los discos de esado solido:}
- \textbf{Capacidad:} Normalmente tienen mas capacidad que los discos
  duros en laptos pero en computadoras de escritorio los discos duros
  ganan en este aspecto. 
- \textbf{Costo:} Aproximadamente custan $0.17 por Gb que los discos
  de estado solido.
# SUBTEMA 2
* Organización de un disco de estado solido
** Organización de un disco de estado solido
:PROPERTIES:
:BEAMER_OPT: shrink=15
:END:
*** texto :BMCOL:
:PROPERTIES:
:BEAMER_COL: 0.55
:END:
- \textbf{Interface:} Es la parte que conecta de manera lógica el ssd
  con el sistema host.
- \textbf{Controller:} Provee ejecucion del firmware.
- \textbf{Direccionador:} Provee la lógica de seleccionamiento de los
  chips NANDS
- \textbf{Cache:} Cache del sistema de memoria para tener mayor
  velocidad.
- \textbf{Correccion de errores:} Componente que se encarga de
  detectar y corregir errores.
- \textbf{Componentes de memoria flash:} Son los chips NANDS
  encargados de guardar la información.
*** Imagen :BMCOL:Imagen:
:PROPERTIES:
:BEAMER_COL: 0.45
:END:
#+BEGIN_EXPORT latex
\begin{center}
\includegraphics[width=0.8\linewidth]{images/organizacion_ssd.png}
\end{center}
#+END_EXPORT

# Danilo
* Problemas Prácticos
** Problemas Prácticos
:PROPERTIES:
:BEAMER_OPT: shrink=20
:END:
La naturaleza electrónica de las celdas Flash NAND introduce
restricciones físicas y operativas muy especificas en el hardware.

\textbf{Desafíos del medio semiconductor:}
- \textbf{ciclos P/E limitados:} Las celdas sufren un desgaste físico
irreversible en su capa aislante tras un numero fijo de escrituras o
borrados. 
- \textbf{Asimetría de bloques y paginas:} Las lecturas y escrituras
  se ocurren a nivel de bloques completos.
- \textbf{Wear Leveling:} Algoritmo integrado en el controlador para
  distribuir de manera homogénea las escrituras en todo el medio y
  evitar sectores muertos prematuros 
- \textbf{Gestión de bloques dañados:} Aislamiento lógico dinámico de
  celdas fallidas para resguardar la integridad de los datos útiles.
*** Ampliación de escritura
Debido a la imposibilidad de sobrescribir datos en una pagina
directamente sin limpiar previamente todo su bloque contenedor, se
produce el fenómeno WAF (\textit{Write Amplification Factor}).

- \textit{Definición:} Ocurre cuando un controlador debe reubicar
  dinámicamente paginas validas a un bloque limpio antes de borrar un
  bloque viejo, generando escrituras internas añadidas.
- \textit{Consecuencia:} Una alta amplificación satura los canales de
  datos y acelera el fin de la vida útil del hardware. \\ 

\vspace{0.3cm}
\hspace{3cm} \(waf + \frac{\text{Datos Escritos en la Memoria
Flash}}{\text{Datos Solicitados por el Host}}\)

#+BEGIN_EXPORT latex
\begin{definition}
El firmware busca aproximar el WAF los mas cercano posible a 1
mediante una recolección de basura optimizada en segundo plano.
\end{definition}
#+END_EXPORT

* Memoria Óptica 
** Disco Compacto
*** texo :BMCOL:
:PROPERTIES:
:BEAMER_COL: 0.6
:END:
El almacenamiento óptico se basa en la reflexión de haces de luz
concentrados sobre una pista continua en espiral.
- \textbf{Pits (Hoyos):} Micro Hendiduras físicas estampadas en la
  superficie de policarbonato que dispersan la luz del láser.
- \textbf{Lands (Llanos):} Regiones intermedias altamente reflectantes
  que devuelven el haz luminoso directamente al foto-diodo receptor.
- \textbf{Codificación Binaria:} Las transiciones físicas entre un pit
  y un land se interpretan como un bit '1', la continuidad se lee como
  bits '0'.

*** Imagen :BMCOL:Imagen:
:PROPERTIES:
:BEAMER_COL: 0.4
:END:

#+BEGIN_EXPORT latex
\begin{center}
\includegraphics[width=1\linewidth]{images/Danilo_imgagen.jpeg}
\end{center}
#+END_EXPORT

** Variables del Formato CD
La literatura de Stallings segmenta los discos compactos en tres
variaciones fundamentales según su capacidad de alternación 

- \textbf{CD-ROM:} Memoria de solo lectura cuyos pits y lands son
  estampados en masa mediante molde de inyección de policarbonato industriales
- \textbf{CD-R:} Disco grabable una única vez,  contiene una capa
  intermedia de tinte orgánico translúcido que el láser quema a alta
  potencia para emular opticamente un pit.
- \textbf{CD-RW:} Medio regrabable estructurado con una aleación
  metálica de fase capaz de alternar entre un estado cristalino
  reflectante y amorfo absorbente.
  
* DVD (Disco Digital  Versátil) 

** Cambios en la llegada del DVD 
:PROPERTIES:
:BEAMER_env: block
:END:
- Sustituto de las cintas VHS de video analógicas.
- Sustituye a las cintas de video usadas en los reproductores de video (VCR).
- Sustituye al CD-ROM en los PC y servidores.

** Ventajas 
:PROPERTIES:
:BEAMER_env: block
:END:
- Proporciona películas con una calidad de imagen impresionante, y se puede
  acceder a ellos aleatoriamente como en los CD de audio, que también pueden leer los DVD.
- En un disco se puede grabar un gran volumen de datos, en la actualidad siete veces más que en un CD-ROM
- Los juegos para PC serán más reales y el software educativo incorporará más vídeo.
  Como (habrá un nuevo pico en el tráfico en Internet e intranets corporativas, ya que este material se incorporará a los sitios web)  
  
** Capacidad del DVD 
:PROPERTIES:
:BEAMER_OPT: shrink=15
:END:
- Los bits se empaquetan más juntos en un DVD. El espacio entre las vueltas de una espiral en un CD es de 1,6 µm y la distancia mínima entre hoyos a lo largo de la espiral es de 0,834 µm.
- El DVD utiliza un láser con una longitud de onda menor y consigue un espaciado entre vueltas de 0,74 µm y una distancia mínima entre hoyos de 0,4 µm.
- El resultado de estas dos mejoras supone un incremento de capacidad en un factor de siete, de alrededor de \textbf{4,7 GB}.
- El DVD utiliza una segunda capa de hoyos y valles sobre la primera capa. Un DVD de doble capa tiene una capa semirreflectante sobre la capa reflectante, ajustando el enfoque, el láser puede leer cada capa por separado. Capacidad hasta \textbf{8,5 GB}.
- El DVD-ROM puede tener dos superficies, mientras que en un CD los datos se graban solo en una superficie. Esto da una capacidad total de más de \textbf{17 GB}.

#+BEGIN_EXPORT latex
\begin{center}
\includegraphics[width=0.45\linewidth]{images/DVD.png}
\end{center}
#+END_EXPORT

* Discos Ópticos de Alta Definición 
** Características 
:PROPERTIES:
:BEAMER_env: block
:END:
- Diseñados para vídeo de alta definición y mayor capacidad que el DVD.
- Usan láser de longitud de onda corta (azul-violeta) para mayor densidad de bits.
- Dos formatos compitieron: \textbf{HD DVD} y \textbf{Blu-ray}.

** Blue-ray 
:PROPERTIES:
:BEAMER_env: block
:BEAMER_OPT: shrink=15
:END:
- Logró la dominancia del mercado.
- Capa de datos más cerca del láser: pistas e impresiones más pequeñas.
- Capacidad de \textbf{25 GB} por capa.
- Tres versiones: \textbf{BD-ROM} (solo lectura), \textbf{BD-R} (grabable una vez), \textbf{BD-RE} (regrabable).

#+BEGIN_EXPORT latex
\begin{center}
\includegraphics[width=0.55\linewidth]{images/AltaDefinicion.png}
\end{center}
#+END_EXPORT
